apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.mysql.image }}"
          ports:
            - containerPort: {{ .Values.mysql.servicePort }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "{{ .Values.mysql.env.MYSQL_ROOT_PASSWORD }}"
            - name: MYSQL_DATABASE
              value: "{{ .Values.mysql.env.MYSQL_DATABASE }}"
