apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-service
  template:
    metadata:
      labels:
        app: notes-service
    spec:
      containers:
        - name: notes-service
          image: ram1uj/notes-app-notes-service
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_NAME
              value: notes_db
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              value: password
          ports:
            - containerPort: 8100